Version 0.1
Dhii/di-interface pull request #1
Opened 2017-01-31 13:18 UTC by mecha

Initial release, containing interop interfaces.

## Added
- Interop interfaces;
- Interface tests.

2017-02-01 13:34 UTC, XedinUnknown requested changes
Looks like an [extra line](https://github.com/Dhii/di-interface/blob/release/0.1/src/FactoryInterface.php#L22)

2017-02-01 14:31 UTC, XedinUnknown approved these changes

2017-02-02 12:46 UTC, XedinUnknown commented
@mecha, one last look please before release.

2017-02-02 13:08 UTC, mecha commented
LGTM 👌

2017-02-02 13:12 UTC, merged